<?php

namespace Database\Seeders;

use App\Models\Operation;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class OperationSedeer extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $operations = [
            ['id' => 1, 'name' => "ADJUDICACION POR REMATE", 'description' => 'ADJUDICACION POR REMATE'],
            ['id' => 2, 'name' => "ADJUDICACION Y CANCELACION DE HIPOTECA", 'description' => 'ADJUDICACION Y CANCELACION DE HIPOTECA'],
            ['id' => 3, 'name' => "ACTA CONSTITUTIVA Y ESTATUTOS PROTOCOLIZ", 'description' => 'ACTA CONSTITUTIVA Y ESTATUTOS PROTOCOLIZ'],
            ['id' => 4, 'name' => "APERTURA DE CREDITO CON GARANTIA HIPO.", 'description' => 'APERTURA DE CREDITO CON GARANTIA HIPO.'],
            ['id' => 5, 'name' => "APLICACION DE BIEN INMUEBLE", 'description' => 'APLICACION DE BIEN INMUEBLE'],
            ['id' => 6, 'name' => "APLICACION DE BIENES POR HERENCIA", 'description' => 'APLICACION DE BIENES POR HERENCIA'],
            ['id' => 7, 'name' => "ASAMBLEA GENERAL. PROTOCOLIZACION", 'description' => 'ASAMBLEA GENERAL. PROTOCOLIZACION'],
            ['id' => 8, 'name' => "CANCELACION DE HIPOTECA", 'description' => 'CANCELACION DE HIPOTECA'],
            ['id' => 9, 'name' => "CAPITULACIONES MATRIMONIALES", 'description' => 'CAPITULACIONES MATRIMONIALES'],
            ['id' => 10, 'name' => "CESION DE DERECHOS HEREDITARIOS", 'description' => 'CESION DE DERECHOS HEREDITARIOS'],
            ['id' => 11, 'name' => "CESION DE DERECHOS LITIGIOSOS", 'description' => 'CESION DE DERECHOS LITIGIOSOS'],
            ['id' => 12, 'name' => "COMPRA VENTA", 'description' => 'COMPRA VENTA'],
            ['id' => 13, 'name' => "COMPRA VENTA Y DONACION", 'description' => 'COMPRA VENTA Y DONACION'],
            ['id' => 14, 'name' => "COMPRA VENTA Y ERECCION", 'description' => 'COMPRA VENTA Y ERECCION'],
            ['id' => 15, 'name' => "COMPRA VENTA Y FUSION", 'description' => 'COMPRA VENTA Y FUSION'],
            ['id' => 16, 'name' => "COMPRA VENTA JUDICIAL", 'description' => 'COMPRA VENTA JUDICIAL'],
            ['id' => 17, 'name' => "CONSOLIDACION DE DERECHOS", 'description' => 'CONSOLIDACION DE DERECHOS'],
            ['id' => 18, 'name' => "CONSTITUCION DE ASOCIACION CIVIL", 'description' => 'CONSTITUCION DE ASOCIACION CIVIL'],
            ['id' => 19, 'name' => "CONSTITUCION DE SOCIEDAD CIVIL", 'description' => 'CONSTITUCION DE SOCIEDAD CIVIL'],
            ['id' => 20, 'name' => "CONSTITUCION DE S.A. DE C.V.", 'description' => 'CONSTITUCION DE S.A. DE C.V.'],
            ['id' => 21, 'name' => "CONSTITUCION DE S.A. DE R.L. DE C.V.", 'description' => 'CONSTITUCION DE S.A. DE R.L. DE C.V.'],
            ['id' => 22, 'name' => "CONSTITUCION DE S. P. R. DE R. L.", 'description' => 'CONSTITUCION DE S. P. R. DE R. L.'],
            ['id' => 23, 'name' => "CONSTITUCION DE S.P.R. DE R.I.", 'description' => 'CONSTITUCION DE S.P.R. DE R.I.'],
            ['id' => 24, 'name' => "CONST. DE REGIMEN DE PROP. EN CONDOMINIO", 'description' => 'CONST. DE REGIMEN DE PROP. EN CONDOMINIO'],
            ['id' => 25, 'name' => "CONTRATO DE TRANSACCION. PROTOCOLIZACION", 'description' => 'CONTRATO DE TRANSACCION. PROTOCOLIZACION'],
            ['id' => 26, 'name' => "CONVENIO MODIFICATORIO. PROTOCOLIZACION", 'description' => 'CONVENIO MODIFICATORIO. PROTOCOLIZACION'],
            ['id' => 27, 'name' => "DACION EN PAGO", 'description' => 'DACION EN PAGO'],
            ['id' => 28, 'name' => "DIVISION DE COSA COMUN", 'description' => 'DIVISION DE COSA COMUN'],
            ['id' => 29, 'name' => "DONACION", 'description' => 'DONACION'],
            ['id' => 30, 'name' => "DONACION Y COMPRA VENTA", 'description' => 'DONACION Y COMPRA VENTA'],
            ['id' => 31, 'name' => "DONACION Y ERECCION", 'description' => 'DONACION Y ERECCION'],
            ['id' => 32, 'name' => "DONACION Y FUSION", 'description' => 'DONACION Y FUSION'],
            ['id' => 33, 'name' => "ERECCION", 'description' => 'ERECCION'],
            ['id' => 34, 'name' => "ERECCION Y COMPRA VENTA", 'description' => 'ERECCION Y COMPRA VENTA'],
            ['id' => 35, 'name' => "ERECCION Y DONACION", 'description' => 'ERECCION Y DONACION'],
            ['id' => 36, 'name' => "FE DE HECHOS", 'description' => 'FE DE HECHOS'],
            ['id' => 37, 'name' => "FUSION DE PREDIOS", 'description' => 'FUSION DE PREDIOS'],
            ['id' => 38, 'name' => "INTERPELACION NOTARIAL", 'description' => 'INTERPELACION NOTARIAL'],
            ['id' => 39, 'name' => "LOTIFICACION", 'description' => 'LOTIFICACION'],
            ['id' => 40, 'name' => "MANDATO GRAL PLEITOS Y COBRANZAS", 'description' => 'MANDATO GRAL PLEITOS Y COBRANZAS'],
            ['id' => 41, 'name' => "MANDATO GRAL P Y C CON ACTOS DE ADMON", 'description' => 'MANDATO GRAL P Y C CON ACTOS DE ADMON'],
            ['id' => 42, 'name' => "MANDATO GRAL P Y C, ADMON Y DOMINIO", 'description' => 'MANDATO GRAL P Y C, ADMON Y DOMINIO'],
            ['id' => 43, 'name' => "MANDATO ESPECIAL", 'description' => 'MANDATO ESPECIAL'],
            ['id' => 44, 'name' => "MANDATO ESPECIAL IRREVOCABLE", 'description' => 'MANDATO ESPECIAL IRREVOCABLE'],
            ['id' => 45, 'name' => "MUTUO CON INTERES Y GARANTIA HIPOTECARIA", 'description' => 'MUTUO CON INTERES Y GARANTIA HIPOTECARIA'],
            ['id' => 46, 'name' => "MUTUO SIMPLE CON GARANTIA HIPOTECARIA", 'description' => 'MUTUO SIMPLE CON GARANTIA HIPOTECARIA'],
            ['id' => 47, 'name' => "OTORGAMIENTO DE ESCRITURA PUBLICA", 'description' => 'OTORGAMIENTO DE ESCRITURA PUBLICA'],
            ['id' => 48, 'name' => "RADICACION TESTAMENTARIA", 'description' => 'RADICACION TESTAMENTARIA'],
            ['id' => 49, 'name' => "RECONOCIMIENTO DE ADEUDO CON GARANTIA HI", 'description' => 'RECONOCIMIENTO DE ADEUDO CON GARANTIA HI'],
            ['id' => 50, 'name' => "RECTIFICACION DE MEDIDAS Y COLINDANCIAS", 'description' => 'RECTIFICACION DE MEDIDAS Y COLINDANCIAS'],
            ['id' => 51, 'name' => "RECTIFICACION DE NOMENCLATURA", 'description' => 'RECTIFICACION DE NOMENCLATURA'],
            ['id' => 52, 'name' => "RECTIFICACION DE SUPERFICIE", 'description' => 'RECTIFICACION DE SUPERFICIE'],
            ['id' => 53, 'name' => "REVOCACION DE MANDATO", 'description' => 'REVOCACION DE MANDATO'],
            ['id' => 54, 'name' => "SERVIDUMBRE LEGAL DE PASO. CONSTITUCION", 'description' => 'SERVIDUMBRE LEGAL DE PASO. CONSTITUCION'],
            ['id' => 55, 'name' => "SUBDIVISION DE PREDIO", 'description' => 'SUBDIVISION DE PREDIO'],
            ['id' => 56, 'name' => "TESTAMENTO PUBLICO ABIERTO", 'description' => 'TESTAMENTO PUBLICO ABIERTO'],
            ['id' => 57, 'name' => "PROTOCOLIZACION DE PODERES", 'description' => 'PROTOCOLIZACION DE PODERES'],
            ['id' => 58, 'name' => "APLICACION DE BIENES HEREDITARIOS Y C-V", 'description' => 'APLICACION DE BIENES HEREDITARIOS Y C-V'],
            ['id' => 59, 'name' => "CANCELACION DE HIP. EREC Y C-V", 'description' => 'CANCELACION DE HIP. EREC Y C-V'],
            ['id' => 60, 'name' => "EREC Y REG DE PROPIEDAD EN CONDOMINIO", 'description' => 'EREC Y REG DE PROPIEDAD EN CONDOMINIO'],
            ['id' => 61, 'name' => "APLICACION DE BIENES HERE. Y DONACION", 'description' => 'APLICACION DE BIENES HERE. Y DONACION'],
            ['id' => 62, 'name' => "FUSION Y DONACION", 'description' => 'FUSION Y DONACION'],
            ['id' => 63, 'name' => "FUSION RECTIFICACION Y C-V", 'description' => 'FUSION RECTIFICACION Y C-V'],
            ['id' => 64, 'name' => "SERVIDUMBRE DE PASO Y DONACION", 'description' => 'SERVIDUMBRE DE PASO Y DONACION'],
            ['id' => 65, 'name' => "CONSOLIDACION Y CV", 'description' => 'CONSOLIDACION Y CV'],
            ['id' => 66, 'name' => "RECTIFICACION Y C-V", 'description' => 'RECTIFICACION Y C-V'],
            ['id' => 67, 'name' => "TERMINACION DE MANDATO", 'description' => 'TERMINACION DE MANDATO'],
            ['id' => 68, 'name' => "SERVI, SUBDIVI, RENUNCIA DE USU, DACION", 'description' => 'SERVI, SUBDIVI, RENUNCIA DE USU, DACION'],
            ['id' => 69, 'name' => "CONSOLIDACION Y DONACION", 'description' => 'CONSOLIDACION Y DONACION'],
            ['id' => 70, 'name' => "CONSOLIDACION Y PERMUTA", 'description' => 'CONSOLIDACION Y PERMUTA'],
            ['id' => 71, 'name' => "COMODATO", 'description' => 'COMODATO'],
            ['id' => 72, 'name' => "DONACION Y DIVISION DE COSA COMUN", 'description' => 'DONACION Y DIVISION DE COSA COMUN'],
            ['id' => 73, 'name' => "TRANS DE PROP Y EXTINCION DE FIDEICOMISO", 'description' => 'TRANS DE PROP Y EXTINCION DE FIDEICOMISO'],
            ['id' => 74, 'name' => "ERECION Y APLICACION DE BIENES", 'description' => 'ERECION Y APLICACION DE BIENES'],
            ['id' => 75, 'name' => "ERECCION, REGIMEN Y C-V", 'description' => 'ERECCION, REGIMEN Y C-V'],
            ['id' => 76, 'name' => "RECTIFICACION Y DIVISION", 'description' => 'RECTIFICACION Y DIVISION'],
            ['id' => 77, 'name' => "EXTINCION DE USU. Y PRESTAMO CON GARANTI", 'description' => 'EXTINCION DE USU. Y PRESTAMO CON GARANTI'],
            ['id' => 78, 'name' => "LIQUIDACION PARCIAL DE SOCIEDAD CONYUGAL", 'description' => 'LIQUIDACION PARCIAL DE SOCIEDAD CONYUGAL'],
            ['id' => 79, 'name' => "PROTOCOLIZACION CONTRATO PRIVADO", 'description' => 'PROTOCOLIZACION CONTRATO PRIVADO'],
            ['id' => 80, 'name' => "RECTI, SERVIDUMBRE, ERECCION Y DONACION", 'description' => 'RECTI, SERVIDUMBRE, ERECCION Y DONACION'],
            ['id' => 81, 'name' => "CONTRATO DE ARRENDAMIENTO", 'description' => 'CONTRATO DE ARRENDAMIENTO'],
            ['id' => 82, 'name' => "PROTOCOLIZACION DE SENTENCIA DE USUCAPIO", 'description' => 'PROTOCOLIZACION DE SENTENCIA DE USUCAPIO'],
            ['id' => 83, 'name' => "PAPEL ABONO", 'description' => 'PAPEL ABONO'],
            ['id' => 84, 'name' => "COMPRA VENTA CON RESERVA DE DOMINIO", 'description' => 'COMPRA VENTA CON RESERVA DE DOMINIO'],
            ['id' => 85, 'name' => "SERVIDUMBRE Y DIVISION DE COPROPIEDAD", 'description' => 'SERVIDUMBRE Y DIVISION DE COPROPIEDAD'],
            ['id' => 86, 'name' => "ERECCION Y LIQUIDACION DE SOCIEDAD CONYU", 'description' => 'ERECCION Y LIQUIDACION DE SOCIEDAD CONYU'],
            ['id' => 87, 'name' => "LIQUIDACION DE SOC. CONYUGAL Y C-V", 'description' => 'LIQUIDACION DE SOC. CONYUGAL Y C-V'],
            ['id' => 88, 'name' => "ADJUDICACION DE BIEN INMUEBLE", 'description' => 'ADJUDICACION DE BIEN INMUEBLE'],
            ['id' => 89, 'name' => "RECTIFICACION DE MEDIDAS Y DONACION", 'description' => 'RECTIFICACION DE MEDIDAS Y DONACION'],
            ['id' => 90, 'name' => "ERECCION, SERVIDUMBRE Y DONACION", 'description' => 'ERECCION, SERVIDUMBRE Y DONACION'],
            ['id' => 91, 'name' => "COMPRA VENTA Y COMODATO", 'description' => 'COMPRA VENTA Y COMODATO'],
            ['id' => 92, 'name' => "ERECCION Y SERVIDUMBRE DE PASO", 'description' => 'ERECCION Y SERVIDUMBRE DE PASO'],
            ['id' => 93, 'name' => "PROTOCOLIZACION SESION DE CONSEJO", 'description' => 'PROTOCOLIZACION SESION DE CONSEJO'],
            ['id' => 94, 'name' => "REVOCACION DE TESTAMENTO", 'description' => 'REVOCACION DE TESTAMENTO'],
            ['id' => 95, 'name' => "PROTO ESCR PRIV Y APLICA DE BIENES HERED", 'description' => 'PROTO ESCR PRIV Y APLICA DE BIENES HERED'],
            ['id' => 96, 'name' => "APLICA DE BIENES, CONSOLIDACION Y DONA", 'description' => 'APLICA DE BIENES, CONSOLIDACION Y DONA'],
            ['id' => 97, 'name' => "CESION DE DERECHOS", 'description' => 'CESION DE DERECHOS'],
            ['id' => 98, 'name' => "PROTOCOLIZACION DE PLANO", 'description' => 'PROTOCOLIZACION DE PLANO'],
            ['id' => 99, 'name' => "DACION EN PAGO Y CANCELACION DE HIPOTECA", 'description' => 'DACION EN PAGO Y CANCELACION DE HIPOTECA'],
            ['id' => 100, 'name' => "CONSOLIDACION, EREC Y CV", 'description' => 'CONSOLIDACION, EREC Y CV'],
            ['id' => 101, 'name' => "FUSION DE PREDIOS Y C-V", 'description' => 'FUSION DE PREDIOS Y C-V'],
            ['id' => 102, 'name' => "MANDATO GENERAL AMPLISIMO", 'description' => 'MANDATO GENERAL AMPLISIMO'],
            ['id' => 103, 'name' => "REPUDIO DE HERENCIA", 'description' => 'REPUDIO DE HERENCIA'],
            ['id' => 104, 'name' => "PROTOCOLIZACION DE DOCUMENTO", 'description' => 'PROTOCOLIZACION DE DOCUMENTO'],
            ['id' => 105, 'name' => "APLICACION DE BIEN INMUEBLE Y ERECCION", 'description' => 'APLICACION DE BIEN INMUEBLE Y ERECCION'],
            ['id' => 106, 'name' => "MANDATO GENERAL Y ESPECIAL", 'description' => 'MANDATO GENERAL Y ESPECIAL'],
            ['id' => 107, 'name' => "ACTA NOTARIAL", 'description' => 'ACTA NOTARIAL'],
            ['id' => 108, 'name' => "RECTIFICACION Y ERECCION", 'description' => 'RECTIFICACION Y ERECCION'],
            ['id' => 109, 'name' => "SERVIDUMBRE DE PASO Y SUBDIVISION", 'description' => 'SERVIDUMBRE DE PASO Y SUBDIVISION'],
            ['id' => 110, 'name' => "CONSTITUCION S. DE R.L.", 'description' => 'CONSTITUCION S. DE R.L.'],
            ['id' => 111, 'name' => "DONACION FUSION Y ERECCION", 'description' => 'DONACION FUSION Y ERECCION'],
            ['id' => 112, 'name' => "ERECCION, CV Y MUTUO", 'description' => 'ERECCION, CV Y MUTUO'],
            ['id' => 113, 'name' => "RECTIFICACION, ERECCION, CV Y MUTUO", 'description' => 'RECTIFICACION, ERECCION, CV Y MUTUO'],
            ['id' => 114, 'name' => "FUSION, ERECCION Y C-V", 'description' => 'FUSION, ERECCION Y C-V'],
            ['id' => 115, 'name' => "ERECCION Y C-V CON RESERVA DE DOMINIO", 'description' => 'ERECCION Y C-V CON RESERVA DE DOMINIO'],
            ['id' => 116, 'name' => "COMPRA-VENTA Y MUTUO C/ GARANTIA", 'description' => 'COMPRA-VENTA Y MUTUO C/ GARANTIA'],
            ['id' => 117, 'name' => "CANCELACION DE HIPOTECA Y C-V", 'description' => 'CANCELACION DE HIPOTECA Y C-V'],
            ['id' => 118, 'name' => "RECTIFICACIO, APLICACION DE BIENES Y C-V", 'description' => 'RECTIFICACIO, APLICACION DE BIENES Y C-V'],
            ['id' => 119, 'name' => "RECTIFICACION Y DONACION", 'description' => 'RECTIFICACION Y DONACION'],
            ['id' => 120, 'name' => "CONSTITUCION DE S. DE R.L. DE C.V.", 'description' => 'CONSTITUCION DE S. DE R.L. DE C.V.'],
            ['id' => 121, 'name' => "PERMUTA", 'description' => 'PERMUTA'],
            ['id' => 122, 'name' => "FUSION Y RECTIFICACION", 'description' => 'FUSION Y RECTIFICACION'],
            ['id' => 123, 'name' => "CANCELACION DE HIP Y TERMINACION PODER", 'description' => 'CANCELACION DE HIP Y TERMINACION PODER'],
            ['id' => 124, 'name' => "APLICA, CV, FUSION Y RECTIFICACION", 'description' => 'APLICA, CV, FUSION Y RECTIFICACION'],
            ['id' => 125, 'name' => "RECTI, EREC, CONSO, APLICA Y CV", 'description' => 'RECTI, EREC, CONSO, APLICA Y CV'],
            ['id' => 126, 'name' => "RESCISION DE CONTRATO", 'description' => 'RESCISION DE CONTRATO'],
            ['id' => 127, 'name' => "CANCELACION DE RESERVA DE DOMINIO", 'description' => 'CANCELACION DE RESERVA DE DOMINIO'],
            ['id' => 128, 'name' => "CANCE HIPOTECA, CV Y APERTURA DE CREDITO", 'description' => 'CANCE HIPOTECA, CV Y APERTURA DE CREDITO'],
            ['id' => 129, 'name' => "SERVIDUMBRE DE PASO Y CV", 'description' => 'SERVIDUMBRE DE PASO Y CV'],
            ['id' => 130, 'name' => "EXTINSION DE FIDEICOMISO Y CANCE DE HIPO", 'description' => 'EXTINSION DE FIDEICOMISO Y CANCE DE HIPO'],
            ['id' => 131, 'name' => "COMPULSA", 'description' => 'COMPULSA'],
            ['id' => 132, 'name' => "DEMOLICION Y EXTINCION DE REGIMEN DE PRO", 'description' => 'DEMOLICION Y EXTINCION DE REGIMEN DE PRO'],
            ['id' => 133, 'name' => "SUBDIVISION, SERVIDUMBRE, EREC Y DONA", 'description' => 'SUBDIVISION, SERVIDUMBRE, EREC Y DONA'],
            ['id' => 134, 'name' => "RECTI, EREC, DIVI Y CV", 'description' => 'RECTI, EREC, DIVI Y CV'],
            ['id' => 135, 'name' => "EREC, APLICA Y DONACION", 'description' => 'EREC, APLICA Y DONACION'],
            ['id' => 136, 'name' => "DIVISION DE COSA COMUN Y DONACION", 'description' => 'DIVISION DE COSA COMUN Y DONACION'],
            ['id' => 137, 'name' => "COMPRA VENTA Y DIVISION", 'description' => 'COMPRA VENTA Y DIVISION'],
            ['id' => 138, 'name' => "CONSTITUCION DE SOCIEDAD COPERATIVA", 'description' => 'CONSTITUCION DE SOCIEDAD COPERATIVA'],
            ['id' => 139, 'name' => "RECTI, FUSION Y CV", 'description' => 'RECTI, FUSION Y CV'],
            ['id' => 140, 'name' => "RECTI, EREC Y CV", 'description' => 'RECTI, EREC Y CV'],
            ['id' => 141, 'name' => "PROTO INVEN, APLICA, DONA, CV", 'description' => 'PROTO INVEN, APLICA, DONA, CV'],
            ['id' => 142, 'name' => "CANCE HIP, EXT FIDEI, EREC, CV, MUTUO GH", 'description' => 'CANCE HIP, EXT FIDEI, EREC, CV, MUTUO GH'],
            ['id' => 143, 'name' => "TRANSMISION DE PROPIEDAD", 'description' => 'TRANSMISION DE PROPIEDAD'],
            ['id' => 144, 'name' => "DIVISION DE COSA COMUN Y ERECCION", 'description' => 'DIVISION DE COSA COMUN Y ERECCION'],
            ['id' => 145, 'name' => "MANDATO GRAL PYC, ADMON LABORAL", 'description' => 'MANDATO GRAL PYC, ADMON LABORAL'],
            ['id' => 146, 'name' => "RECTIFICACION", 'description' => 'RECTIFICACION'],
            ['id' => 147, 'name' => "MANDATO GRAL PYC ADMON SIN INSCRIPCION", 'description' => 'MANDATO GRAL PYC ADMON SIN INSCRIPCION'],
            ['id' => 148, 'name' => "PROTO INVEN, FUSION, EREC Y APLICACION", 'description' => 'PROTO INVEN, FUSION, EREC Y APLICACION'],
            ['id' => 149, 'name' => "EREC CANCE HIP CV MUTUO GARANTIA HIPOTEC", 'description' => 'EREC CANCE HIP CV MUTUO GARANTIA HIPOTEC'],
            ['id' => 150, 'name' => "MANDATO GENERAL SIN INSCRIPCION", 'description' => 'MANDATO GENERAL SIN INSCRIPCION'],
            ['id' => 151, 'name' => "DONA, EREC, CV Y MUTUO C/G HIPOTECARIA", 'description' => 'DONA, EREC, CV Y MUTUO C/G HIPOTECARIA'],
            ['id' => 152, 'name' => "CANCELACION DE HIPOTECA Y ERECCIÓN", 'description' => 'CANCELACION DE HIPOTECA Y ERECCIÓN'],
            ['id' => 153, 'name' => "COMPRA VENTA Y MANDATO", 'description' => 'COMPRA VENTA Y MANDATO'],
            ['id' => 154, 'name' => "CONSTITUCION DE HIPOTECA", 'description' => 'CONSTITUCION DE HIPOTECA'],
            ['id' => 155, 'name' => "RECTIFI, EREC, SUBDIVISION Y SERVIDUMBRE", 'description' => 'RECTIFI, EREC, SUBDIVISION Y SERVIDUMBRE'],
            ['id' => 156, 'name' => "CONSTITUCION SAPI DE CV", 'description' => 'CONSTITUCION SAPI DE CV'],
            ['id' => 157, 'name' => "PROTO CONSTITUTIVA Y ESTATUTOS", 'description' => 'PROTO CONSTITUTIVA Y ESTATUTOS'],
            ['id' => 158, 'name' => "CANCELACION DE HIP Y RECTIFICACION", 'description' => 'CANCELACION DE HIP Y RECTIFICACION'],
            ['id' => 159, 'name' => "ERECCION, REGIMEN Y DONACION", 'description' => 'ERECCION, REGIMEN Y DONACION'],
            ['id' => 160, 'name' => "SUBDIVISION DE PREDIO Y CV", 'description' => 'SUBDIVISION DE PREDIO Y CV'],
            ['id' => 161, 'name' => "SEGREGACION Y ERECCION", 'description' => 'SEGREGACION Y ERECCION'],
            ['id' => 162, 'name' => "OTORGAMIENTO DE ESCRITURA Y CV", 'description' => 'OTORGAMIENTO DE ESCRITURA Y CV'],
            ['id' => 163, 'name' => "RECTIFICACION Y ADJUDICACION DE BIEN HER", 'description' => 'RECTIFICACION Y ADJUDICACION DE BIEN HER'],
            ['id' => 164, 'name' => "RADICACION INTESTAMENTARIA", 'description' => 'RADICACION INTESTAMENTARIA'],
            ['id' => 165, 'name' => "CANCELACION DE HIPOTECA Y MUTUO C/GARANT", 'description' => 'CANCELACION DE HIPOTECA Y MUTUO C/GARANT'],
            ['id' => 166, 'name' => "DISOLUCION Y/O RESCISION DE DONACIÓN", 'description' => 'DISOLUCION Y/O RESCISION DE DONACIÓN'],
            ['id' => 167, 'name' => "FIDEICOMISO IRREVOCABLE DE GARANTIA", 'description' => 'FIDEICOMISO IRREVOCABLE DE GARANTIA'],
            ['id' => 168, 'name' => "MANDATO GRAL ACTOS DE ADMINISTRACIÓN", 'description' => 'MANDATO GRAL ACTOS DE ADMINISTRACIÓN'],
            ['id' => 169, 'name' => "REVOCACIÓN DE MANDATO Y COMPRA VENTA", 'description' => 'REVOCACIÓN DE MANDATO Y COMPRA VENTA'],
            ['id' => 170, 'name' => "RECTIFICACIÓN, ERECCIÓN Y DACIÓN EN PAGO", 'description' => 'RECTIFICACIÓN, ERECCIÓN Y DACIÓN EN PAGO'],
            ['id' => 171, 'name' => "SUBDIVISIÓN, APLICACIÓN Y DONACIÓN", 'description' => 'SUBDIVISIÓN, APLICACIÓN Y DONACIÓN'],
            ['id' => 172, 'name' => "ERECCIÓN, APLICACIÓN, SUBDIVI, DONACIÓN", 'description' => 'ERECCIÓN, APLICACIÓN, SUBDIVI, DONACIÓN'],
            ['id' => 173, 'name' => "APLICA, SUBDIVI, SERVIDUMBRE, DONACIÓN", 'description' => 'APLICA, SUBDIVI, SERVIDUMBRE, DONACIÓN'],
            ['id' => 174, 'name' => "APLIC, ADJ HEREDITARIO, SUBDI Y DONACION", 'description' => 'APLIC, ADJ HEREDITARIO, SUBDI Y DONACION'],
            ['id' => 175, 'name' => "ERECC, APLICA, CV", 'description' => 'ERECC, APLICA, CV'],
            ['id' => 176, 'name' => "ERECCIÓN Y DACIÓN EN PAGO", 'description' => 'ERECCIÓN Y DACIÓN EN PAGO'],
            ['id' => 177, 'name' => "ERECCIÓN Y APLICACIÓN DE BIENES HEREDITA", 'description' => 'ERECCIÓN Y APLICACIÓN DE BIENES HEREDITA'],
            ['id' => 178, 'name' => "RECONOCIMIENTO DE ADEUDO Y DACIÓN EN PAG", 'description' => 'RECONOCIMIENTO DE ADEUDO Y DACIÓN EN PAG'],
            ['id' => 179, 'name' => "APERTURA DE CRÉDITO EN CUENTA CORRIENTE", 'description' => 'APERTURA DE CRÉDITO EN CUENTA CORRIENTE'],
            ['id' => 180, 'name' => "ERECCIÓN, RÉGIMEN Y OTORGAMIENTO DE ESCR", 'description' => 'ERECCIÓN, RÉGIMEN Y OTORGAMIENTO DE ESCR'],
            ['id' => 181, 'name' => "RENUNCIA, PRESTAMO Y FIDEICOMISO", 'description' => 'RENUNCIA, PRESTAMO Y FIDEICOMISO'],
            ['id' => 182, 'name' => "RESCISIÓN, CANCE, GARANTIA Y FIDEICOMISO", 'description' => 'RESCISIÓN, CANCE, GARANTIA Y FIDEICOMISO'],
            ['id' => 183, 'name' => "SERVIDUMBRE, EREC Y DONACIÓN", 'description' => 'SERVIDUMBRE, EREC Y DONACIÓN'],
            ['id' => 184, 'name' => "FIANZA", 'description' => 'FIANZA'],
            ['id' => 185, 'name' => "ACTA DE SUCESIÓN INTESTAMENTARIA", 'description' => 'ACTA DE SUCESIÓN INTESTAMENTARIA'],
            ['id' => 186, 'name' => "RECONOCIMIENTO DE ADEUDO", 'description' => 'RECONOCIMIENTO DE ADEUDO'],
            ['id' => 187, 'name' => "MANDATO GENERAL DE PROCURADURIA JUDICIAL", 'description' => 'MANDATO GENERAL DE PROCURADURIA JUDICIAL'],
            ['id' => 188, 'name' => "REGIMEN EN CONDOMINIO Y CV", 'description' => 'REGIMEN EN CONDOMINIO Y CV'],
            ['id' => 189, 'name' => "MUTUO SIMPLE", 'description' => 'MUTUO SIMPLE'],
            ['id' => 190, 'name' => "RECTIFICACIÓN, ERECCIÓN Y DONACIÓN", 'description' => 'RECTIFICACIÓN, ERECCIÓN Y DONACIÓN'],
            ['id' => 191, 'name' => "CANCELACIÓN DE HIPOTECA Y DONACIÓN", 'description' => 'CANCELACIÓN DE HIPOTECA Y DONACIÓN'],
            ['id' => 192, 'name' => "APLICACION, CONSOLIDACIÓN Y COMPRA VENTA", 'description' => 'APLICACION, CONSOLIDACIÓN Y COMPRA VENTA'],
            ['id' => 193, 'name' => "COMPRA VENTA A PLAZOS", 'description' => 'COMPRA VENTA A PLAZOS'],
            ['id' => 194, 'name' => "SUBDIVISIÓN DE PRECIO Y CV", 'description' => 'SUBDIVISIÓN DE PRECIO Y CV'],
            ['id' => 195, 'name' => "RESCISION DE CONTRATO, SEGREGACION Y CV", 'description' => 'RESCISION DE CONTRATO, SEGREGACION Y CV'],
            ['id' => 196, 'name' => "APLICACIÓN, SUBDIVISIÓN, SERVI Y EREC", 'description' => 'APLICACIÓN, SUBDIVISIÓN, SERVI Y EREC'],
            ['id' => 197, 'name' => "DONACION Y EXTENCION DE FIDEICOMISO", 'description' => 'DONACION Y EXTENCION DE FIDEICOMISO'],
            ['id' => 198, 'name' => "SEGREGA, TRANSMISIÓN DE PROP., EXTINSIÓN", 'description' => 'SEGREGA, TRANSMISIÓN DE PROP., EXTINSIÓN'],
            ['id' => 199, 'name' => "SEGREGACIÓN Y DONACIÓN", 'description' => 'SEGREGACIÓN Y DONACIÓN'],
            ['id' => 200, 'name' => "AMPLIACION DE CONST. Y DONACION", 'description' => 'AMPLIACION DE CONST. Y DONACION'],
            ['id' => 201, 'name' => "RÉGIMEN DE PROPIEDAD EN CONDOMINIO", 'description' => 'RÉGIMEN DE PROPIEDAD EN CONDOMINIO'],
            ['id' => 202, 'name' => "RECTI, SERVI, SUBDIVI, CV Y EREC", 'description' => 'RECTI, SERVI, SUBDIVI, CV Y EREC'],
            ['id' => 203, 'name' => "SEGREGACIÓN, ERECCIÓN Y CV", 'description' => 'SEGREGACIÓN, ERECCIÓN Y CV'],
            ['id' => 204, 'name' => "REVERSIÓN DE PROPIEDAD Y EXTINCIÓN DE FI", 'description' => 'REVERSIÓN DE PROPIEDAD Y EXTINCIÓN DE FI'],
        ];

        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('operations')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        foreach ($operations as $operation) {
            print_r('Creando Operación');
            print_r($operation);
            print_r("--- \n");
            Operation::create($operation);
        }
    }
}
