<?php

namespace Database\Seeders;

use App\Models\Stake;
use Illuminate\Database\Seeder;

class StakeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $stakes = [
            "ADQUIRENTE",
            "GESTOR OFICIOSO",
            "ENAJENANTE",
            "MANDATARIO",
            "MANDANTE",
            "SOCIO",
            "SOCIA",
            "ALBA.HERED.DONATARIA",
            "HEREDERO Y DONATARIO",
            "DONANTE",
            "DE CUJUS",
            "DONATARIA",
            "NUDO PROPIETARIO",
            "PERSONA MORAL",
            "DELEGADO ESPECIAL",
            "VENDEDOR",
            "COMPRADOR",
            "CONSTITUTIVA",
            "ASOCIADO",
            "MUTUANTE",
            "MUTUARIO",
            "DEUDOR",
            "ACREEDOR",
            "GARANTE HIPOTECARIO",
            "ADMINISTRADOR UNICO",
            "SOLICITANTE",
            "TESTADOR",
            "TESTIGO",
            "SOLICIANTE",
            "COMRADOR",
            "ADJUDICATARIO",
            "ASOCIACION",
            "VENDEDORA",
            "DONATARIO",
            "MANDATARIA",
            "PRESIDENTE",
            "TESORERO",
            "REPRESENTANTE LEGAL",
            "SECRETARIO",
            "MMANDATARIO",
            "APODERADO GRAL",
            "ACREDITANTE",
            "REPRESENTANTE",
            "ACREDITADO",
            "ENAJENATE",
            "COMPRADORA",
            "NO PASO",
            "CIUDADANO JUEZ",
            "ADJUDICANTE",
            "TESTADORA",
            "DELEGADO ESTATAL",
            "ADJUDICATARIA",
            "DEMANDADO",
            "DONANTE Y SOLICITANT",
            "APODERADO LEGAL",
            "ACREDITADO Y GARANTE",
            "ACREDITADO Y NUDO PR",
            "USUFRUCTUARIO",
            "USUFRUCTUARIA",
            "TRADUCTOR",
            "ACREDITADA",
            "APODERADA LEGAL",
            "CEDENTE",
            "CESIONARIA",
            "CONSTITUIDA",
            "ACCIONISTA",
            "ARRENDADORA",
            "COPROPIETARIA",
            "ARRENDATARIO",
            "FIADOR",
            "ACREEDOR/ACREDITANTE",
            "SOCIEDAD",
            "ACREEDORA",
            "DONANTES",
            "OBLIGADO SOLIDARIO",
            "DEUDORA",
            "ASOCIADA",
            "ASOCIADOS",
            "NUDA PROPIETARIA",
            "DIRECTOR GENERAL",
            "EMPRESA",
            "MUTUARIA",
            "APODERADO",
            "JUEZ 12 DE LO CIVIL",
            "PRESIDENTE ESTATAL",
            "HEREDERA",
            "APODERADA",
            "ENEJENANTE",
            "PRESIDENTE DEL CONSE",
            "TESORERO DEL CONSEJO",
            "ADQUIRENTES",
            "JUEZ DEL REGISTRTO C",
            "VENDEDORES",
            "ARRENDADOR",
            "GERENTE GENERAL",
            "NUDA PROPIEDAD",
            "OTORGANTE",
            "DEMANDADA",
            "GESTOR OFICIOSA",
            "CESIONARIO",
            "NUDO POPRIETARIO",
            "JUEZ DE LO CIVIL",
            "MUTUARIO Y GARANTE",
            "MUTUARIO Y GARANTE H",
            "ALBACEA Y HEREDERA",
            "DONANTE Y VENDEDORA",
            "DONANTE Y VENDEDOR",
            "NUDA PROPITARIA",
            "DOATARIA",
            "ABONADORA",
            "REPRESENTANTES",
            "GARANTE HIPOTECARIA",
            "LA ABONADORA",
            "REVISOR",
            "DOANTARIA",
            "COMISIONADO",
            "HEREDERO",
            "ADMINISTRADOR",
            "LEGATARIA",
            "ADQUIRIENTE",
            "AMNDANTE",
            "MANDNANTE",
            "MANDATE",
            "COPRADORA",
            "MUTUNTE",
            "NUDO PROPIETRIO",
            "APODERDO LEGAL",
            "OGLIGADO SOLIDARIO",
            "SECRETARIO GENERAL",
            "ACREDITADO  Y GARANT",
            "ENAJENANTE Y ADJUDIC",
            "MADATARIO",
            "COHEREDERO",
            "COHEREDERA",
            "CUJUS",
            "DONATAIRA",
            "NUDO PROPITARIO",
            "ALBACEA Y HEREDERO",
            "REPRESENTATE",
            "PERMUTANTE",
            "ENAJENANTE Y APODERA",
            "VENDEDOR Y DONANTE",
            "COMPRADOR Y DONATARI",
            "CONSTITUCION",
            "VICEPRESIDENTE",
            "COMRADORA",
            "SECRETARIA",
            "DONATARIO MENOR",
            "OTORGANTE JUEZ DE LO",
            "MUTUARIOS",
            "APODERADO GENERAL",
            "CECIONARIO",
            "ALBACEA DEFINITIVO",
            "APODERADA Y JEFA DEL",
            "A FAVOR",
            "HEREDERA UNIVERSAL",
            "DE  CUJUS",
            "ALBACEA",
            "LEGATARIO",
            "NUDO PROPIETRARIO",
            "COPROPIETARIO",
            "OTORGA",
            "APODERADA GENERAL",
            "VOCAL",
            "ACREDOR",
            "PRESIDENTA",
            "SOLICITANTE, DONANTE",
            "S. DE P. R. DE R. I.",
            "ALBACEA PROVISIONAL",
            "A.C.",
            "EN REBELDIA",
            "DELEGADA ESPECIAL",
            "SOCIEDAD CIVIL",
            "DONATRIA",
            "MANDARIO",
            "VEDEDORA",
            "CONSTITUCION DE SOCI",
            "ENAJENANTE EN REPRES",
            "ESTOR OFICIOSA",
            "ABOGADA",
            "DEUDOR SOLIDARIO",
            "S. DE P.R. DE R.I.",
            "VENDEDO",
            "DELEGADO ESPECIA",
            "CONTRATANTE",
            "SOCIA ACCIONISTA",
            "DONATORIO",
            "CECIONARIA",
            "APODERADA LEAL",
            "JEFE DE COBRANZA",
            "REPUDIANTE",
            "COOPROPIETARIO",
            "ALBACEA  Y HEREDERA",
            "EL CEDENTE",
            "EL CESIONARIO",
            "A FAVOR DE",
            "ALBCEA Y HEREDERA",
            "SOLICITA",
            "ALBACEA Y ADJUDICATA",
            "DONARARIA",
            "ALBACEA TESTAMENTARI",
            "HEREDERA Y ALBACEA",
            "COPROPIETRIA",
            "PRESIDENTA DEL CONSE",
            "SECRETARIO DEL CONSE",
            "ASOCIACION CIVIL",
            "TUTOR PRINCIPAL",
            "CURADOR",
            "ENAJENANTE Y ALBACEA",
            "REPRESENTANTR",
            "ALBACEA DEFINITIVA",
            "HEREDERO UNIVERSAL",
            "PROPITARIA",
            "ACREEDOR MUTUANTE",
            "DEUDOR MUTUARIO",
            "JUEZ DECIMO PRIMERO",
            "QUIEN AUTORIZA",
            "EN FAVOR",
            "ENAJENANJTE",
            "GESTOR OFICIOSO",
            "DELEGADO",
            "NUDA PROPIESTARIA",
            "PROPIETARIA",
            "ACREEDITADO",
            "COOPROPIETARIA",
            "VICE-PRESIDENTE EJEC",
            "VICE-PRESIDENTE FINA",
            "VICE-PRESIDENTE ADMI",
            "ASESOR INTERNO",
            "NUDA PROPIETARIO",
            "DIRECTORA GENERAL",
            "DIRECTOR",
            "ADMINISTRADORA",
            "MANDATA5RIO",
            "HEREDERA Y COMPRADOR",
            "ENAJENANE",
            "VENDEDOR Y SOLICITAN",
            "COMODATARIA",
            "COMODANTE",
            "SOLICITANTE Y VENDED",
            "MUTUATE",
            "VENDERORA",
            "ADQUIRENTE DE USUFRU",
            "DONATARIA Y SOLICITA",
            "PDTE DEL CONSEJO",
            "SRIO DEL CONSEJO",
            "ADUIQENTE",
            "ADUIRENTE",
            "TUTOR",
            "DNATARIA",
            "ADQUIRENTE DEL USUFR",
            "ADQUIRENTE DE LA NUD",
            "PESONA MORAL",
            "TSTIGO",
            "TESORERA",
            "ALBACEA Y HEREDERO U",
            "ALBACEA Y HEREDERA U",
            "ADQUIERENTE",
            "JEFE DE AREA",
            "ADREDITADO",
            "CESIONARIO-ACREEDOR",
            "ENANJENATE",
            "ACCIONISTAS",
            "PRESIDENTE DE CONSEJ",
            "ALBACEA Y HERDERO UN",
            "ENAJEANTE",
            "ACEDITADO",
            "ALBACEA HEREDERO",
            "DONANTE Y HEREDERA",
            "ADQUIRENTENTE",
            "DANATARIA",
            "DELAGADO ESPECIAL",
            "C. JUEZ SEGUNDO",
            "DEMANDA",
            "PDNTE. DEL CONSEJO",
            "COMISARIO",
            "REPRE Y MANDATARIO",
            "REPRESENTANE LEGAL",
            "ACEDITANTE",
            "GESTOR",
            "ADQURENTE",
            "REPRESENTANE",
            "REVOCADO",
            "HEREDERO Y ALBACEA",
            "EN REPRESENTACION",
            "HEREDERA Y DONANTE",
            "EL DE CUJUS",
            "USUFRUCTUAIRIO",
            "MUTUANTES",
            "A BIENES",
            "COMPARECIENTES",
            "COMPRECIENTE",
            "SUBDIRECTOR",
            "ANAJENANTE",
            "ENAJENTE",
            "ADQUI RENTE",
            "ADQUIENTE",
            "ADQURIENTE",
            "ACREEDOR 2do LUGAR",
            "ACREEDOR 1er LUGAR",
            "MANDATARIO",
            "DOCTOR",
            "MANDATARIO",
            "REVOCANTE",
            "JUEZ DECIMO SEGUNDO",
            "JUEZ 9o. DE LO CIVIL",
            "APODERADOS LEGALES",
            "SOLICTANTE",
            "JUEZ 10 DE LO CIVIL",
            "ALBACE DEFINITIVO",
            "ADJUDICATARIA Y DONA",
            "FIRMA A RUEGO Y ENCA",
            "FIDUCIARIO",
            "DELEGADO FIDUCIARIO",
            "ADQUIRENTE Y GESTOR",
            "REPRESENTADA",
            "DELEGADA",
            "DIRECTO GENERAL",
            "A QUIEN SE REVOCA",
            "REPRESENTEN LEGAL",
            "DECLARANTE",
        ];

        foreach ($stakes as $stake){
            $record = new Stake();
            $record->name = $stake;
            $record->save();
        }
    }
}
